name: supreme-court-topics
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Core data science stack
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0

  # Web scraping
  - requests>=2.25.0
  - beautifulsoup4>=4.9.0
  - lxml>=4.6.0

  # Natural language processing
  - nltk>=3.6.0

  # Development and debugging
  - jupyter>=1.0.0
  - ipython>=7.0.0

  # Optional: Performance improvements
  - numba>=0.56.0
  - joblib>=1.1.0

  # Development tools
  - black>=22.0.0
  - flake8>=4.0.0
  - pytest>=6.0.0

  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - textblob>=0.17.0
    - spacy>=3.4.0
    - gensim>=4.1.0
    - umap-learn>=0.5.0